spring.application.name=oauth2-reference-server
management.server.port=8081
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
forward-headers-strategy: framework

#Request handling is dominated by short blocking calls, so platform threads spend most of their time waiting.
# --> enable virtual threads
spring.threads.virtual.enabled=true